//
//  Localization.swift
//  AntiPhishing
//
//  In-app runtime localization (English / Hebrew), ported from the Android
//  string.xml + values-iw/string.xml. The app toggles language at runtime
//  via the globe button, exactly like the Android app, so we resolve strings
//  manually rather than relying on the system locale.
//

import Foundation

enum L10n {

    private static let en: [String: String] = [
        "app_name": "AntiPhishing",
        "system_protected": "System Protected",
        "protection_disabled": "Protection Disabled",
        "welcome_message": "Your device is being monitored for phishing attempts in real-time.",
        "active_protection": "Active Protection",
        "stats_scanned_today": "Scanned Today",
        "stats_threats_blocked": "Threats Blocked",
        "recent_activity": "Recent Activity",
        "clear_history": "Clear All History",
        "target_browser_label": "Open safe links in:",
        "change_language": "Change Language",
        "scan_qr": "Scan QR Code to check",
        "check_link": "Check a link",
        "paste_link": "Paste or type a link",
        "check_button": "Check Link",
        "enable_protection_first": "Enable protection first to scan QR codes",
        "open_in_safari": "Safari",
        "open_in_app": "In-app browser",
        // Result screens
        "checking_link": "Checking link safety...",
        "checking_qr": "Checking QR code safety...",
        "dangerous_blocked": "Dangerous Link Blocked",
        "dangerous_subtitle": "This link matches a risk signal. Going back is the safer choice.",
        "risk_level": "Risk level",
        "high_risk": "High risk",
        "source": "Source",
        "go_back": "Go Back",
        "open_anyway": "Open Anyway (At Your Own Risk)",
        "link_needs_review": "Link Needs Review",
        "review_subtitle": "We could not confirm this link as safe yet. If you are not sure, going back is the better choice.",
        "status": "Status",
        "unknown": "Unknown",
        "open_link": "Open Link",
        "could_not_check": "Could Not Check Link",
        "server_unreachable": "Server unreachable. The link could not be verified.",
        "safe_message": "The link you entered is not malicious. You are safe 😊",
        "qr_safe_message": "The QR code you scanned is not malicious. You are safe 😊",
        "scan_qr_title": "Scan QR Code",
        "point_camera": "Point your camera at a QR code",
        "camera_permission": "Camera permission is required to scan QR codes",
        "close": "Close",
        "no_link_found": "No valid link found in the text.",
        // Activation flow
        "activate_title": "Activate Protection",
        "activate_intro": "iOS protects links a little differently from Android.",
        "activate_step_share": "Open any link with Share → AntiPhishing (Safari, Messages, WhatsApp, Mail…) to check it first.",
        "activate_step_qr": "Or scan a QR code, or paste a link on the home screen.",
        "activate_step_safe": "Safe links — and ones you choose to continue — open in your default browser.",
        "activate_note": "Tip: choose which browser safe links open in below. iOS only lets full browser apps be the default, so AntiPhishing checks links through Share instead of replacing your browser.",
        "open_settings": "Open Default Browser Settings",
        "activate_done": "Activate Protection",
        "verifying_protection": "Checking that protection works…",
        "protection_active_banner": "✅ Protection active — link checking works",
        "protection_active_offline": "⚠️ Protection on, but the checking service is unreachable",
        "protection_off_banner": "Protection turned off",
        // Safari Web Extension protection
        "safari_protection_title": "Safari Protection",
        "sp_status_storage_error": "Shared storage unavailable",
        "sp_status_storage_error_detail": "The app cannot access its shared storage, so protection data cannot be saved. Try reinstalling the app.",
        "sp_status_updating": "Updating protection database…",
        "sp_status_updating_detail": "Downloading the latest threat data.",
        "sp_status_no_db": "Protection not ready",
        "sp_status_no_db_detail": "The protection database has not been downloaded yet. Download it to protect Safari.",
        "sp_status_no_db_offline": "No connection — protection not ready",
        "sp_status_no_db_offline_detail": "There is no internet connection and no local database yet. Connect to the internet and try again.",
        "sp_status_active": "Protection active",
        "sp_status_active_detail": "Safari is protected with up-to-date threat data.",
        "sp_status_update_available": "Protection active — update available",
        "sp_status_update_available_detail": "The server has newer threat data than your local copy. Update to stay fully protected.",
        "sp_status_active_stale": "Protection active — database is old",
        "sp_status_active_stale_detail": "The local database has not been updated recently. Update when possible.",
        "sp_status_offline": "Protection active — offline",
        "sp_status_offline_detail": "The update service is unreachable. Safari is protected with the last downloaded database.",
        "sp_status_update_failed": "Last update failed",
        "sp_status_update_failed_detail": "The previous database is still active and protecting Safari. Try updating again.",
        "sp_master_off_detail": "Active Protection is turned off, so Safari pages are not being checked. Turn it on from the home screen.",
        "sp_ext_enabled": "Safari extension is active",
        "sp_ext_not_detected": "Safari extension not detected",
        "sp_ext_last_seen": "Last activity:",
        "sp_ext_not_detected_detail": "iOS requires you to enable the extension yourself in Settings and approve website access.",
        "sp_ext_guide_button": "How to Enable the Safari Extension",
        "sp_toast_toggle": "Show check confirmation in Safari",
        "sp_toast_toggle_detail": "While on, every page opened in Safari shows a brief status banner — checked safe, database missing, or protection off. An easy end-to-end test; turn off for quiet browsing.",
        "sp_db_section": "Protection Database",
        "sp_db_version": "Version",
        "sp_db_updated": "Last updated",
        "sp_db_domains": "Protected domains (on device)",
        "sp_db_server_domains": "Domains on server",
        "sp_db_checked": "Last checked",
        "sp_db_none": "No database downloaded yet. Safari cannot be protected until it is downloaded.",
        "sp_download_button": "Download Protection Database",
        "sp_update_button": "Update Protection Database",
        "sp_note_safari_only": "The AntiPhishing extension protects Safari only. If another browser (such as Chrome) is your default, links open there unprotected — consider making Safari your default browser.",
        "sp_progress_left": "left",
        "sp_checking_freshness": "Checking for updates…",
        "sp_db_duration": "Last update took",
        "sp_feed_issues": "Some sources had problems in the last update:",
        "sp_recent_visits_title": "Recently Checked in Safari",
        "sp_recent_visits_empty": "No pages checked yet. Browse in Safari with the extension enabled and they will appear here.",
        "sp_visit_verdict_safe": "Safe",
        "sp_visit_verdict_malicious": "Blocked",
        "sp_visit_verdict_allowlisted": "Approved",
        "sp_visit_verdict_off": "Protection off",
        "sp_visit_verdict_unprotected": "Not protected",
        "sp_phase_contacting": "Contacting server…",
        "sp_phase_downloading": "Downloading threat feeds…",
        "sp_phase_building": "Building database…",
        "sp_phase_validating": "Validating downloaded data…",
        "sp_phase_activating": "Activating new database…",
        "sp_update_success": "✅ Database updated successfully",
        "sp_update_already_current": "✅ Database is already up to date",
        "err_update_storage": "Shared storage is unavailable — the database cannot be saved.",
        "err_update_offline_db": "Could not reach the update sources. Safari stays protected with the last downloaded database.",
        "err_update_offline_nodb": "Could not download the database. Check your internet connection and try again.",
        "err_update_invalid_data": "The downloaded data was invalid and was not activated. The previous database remains in use.",
        "err_update_generic": "The update failed. The previous database remains in use.",
        // Enable-extension guide
        "ext_guide_title": "Enable the Safari Extension",
        "ext_guide_intro": "Apple requires you to enable Safari extensions yourself. It takes about a minute:",
        "ext_guide_step1": "Open Settings ▸ Apps ▸ Safari ▸ Extensions (on older iOS versions: Settings ▸ Safari ▸ Extensions).",
        "ext_guide_step2": "Tap AntiPhishing and turn on Allow Extension.",
        "ext_guide_step3": "Under Permissions, allow access for All Websites so pages can be checked.",
        "ext_guide_step4": "Return here — the status updates after the extension checks its first page in Safari.",
        "ext_guide_note": "The extension checks page addresses against the threat database stored on your device first, entirely offline. Only when a site isn't already known safe or malicious is its address sent to AntiPhishing's server for a deeper risk check.",
        "ext_guide_open_settings": "Open Settings",
        // Allowlist management
        "allowlist_title": "Approved Domains",
        "allowlist_empty": "No approved domains. When you tap \"Continue Anyway\" on a warning page in Safari, the domain will appear here.",
        "allowlist_footer": "Approvals expire automatically after 24 hours. Removing an approval re-enables blocking for that domain.",
        "allowlist_clear_expired": "Remove Expired",
        "allowlist_clear_all": "Remove All",
        "allowlist_clear_all_confirm": "Remove all approved domains? Blocking will resume for all of them.",
        "allowlist_approved": "Approved:",
        "allowlist_expires": "Expires",
        "allowlist_expired_at": "Expired",
        "allowlist_expired": "Expired"
    ]

    private static let he: [String: String] = [
        "app_name": "AntiPhishing",
        "system_protected": "המערכת מוגנת",
        "protection_disabled": "ההגנה כבויה",
        "welcome_message": "המכשיר שלך מנוטר כעת מפני ניסיונות פישינג בזמן אמת.",
        "active_protection": "הגנה פעילה",
        "stats_scanned_today": "נסרקו היום",
        "stats_threats_blocked": "איומים שנחסמו",
        "recent_activity": "פעילות אחרונה",
        "clear_history": "נקה היסטוריה",
        "target_browser_label": "פתח קישורים בטוחים ב:",
        "change_language": "שינוי שפה",
        "scan_qr": "סרוק קוד QR לבדיקה",
        "check_link": "בדיקת קישור",
        "paste_link": "הדבק או הקלד קישור",
        "check_button": "בדוק קישור",
        "enable_protection_first": "הפעל הגנה תחילה כדי לסרוק קודי QR",
        "open_in_safari": "Safari",
        "open_in_app": "דפדפן מובנה",
        // Result screens
        "checking_link": "בודק את בטיחות הקישור...",
        "checking_qr": "בודק את בטיחות קוד ה-QR...",
        "dangerous_blocked": "קישור מסוכן נחסם",
        "dangerous_subtitle": "הקישור תואם לסימן סיכון. לחזור אחורה היא הבחירה הבטוחה יותר.",
        "risk_level": "רמת סיכון",
        "high_risk": "סיכון גבוה",
        "source": "מקור",
        "go_back": "חזור אחורה",
        "open_anyway": "פתח בכל זאת (על אחריותך)",
        "link_needs_review": "הקישור דורש בדיקה",
        "review_subtitle": "לא הצלחנו לאשר את הקישור כבטוח. אם אינך בטוח, עדיף לחזור אחורה.",
        "status": "סטטוס",
        "unknown": "לא ידוע",
        "open_link": "פתח קישור",
        "could_not_check": "לא ניתן לבדוק את הקישור",
        "server_unreachable": "השרת אינו זמין. לא ניתן היה לאמת את הקישור.",
        "safe_message": "הקישור שהזנת אינו זדוני. אתה מוגן 😊",
        "qr_safe_message": "קוד ה-QR שסרקת אינו זדוני. אתה מוגן 😊",
        "scan_qr_title": "סריקת קוד QR",
        "point_camera": "כוון את המצלמה אל קוד QR",
        "camera_permission": "נדרשת הרשאת מצלמה כדי לסרוק קודי QR",
        "close": "סגור",
        "no_link_found": "לא נמצא קישור תקין בטקסט.",
        // Activation flow
        "activate_title": "הפעלת הגנה",
        "activate_intro": "ב-iOS ההגנה על קישורים עובדת מעט אחרת מאשר באנדרואיד.",
        "activate_step_share": "פתח כל קישור דרך שיתוף ← AntiPhishing (Safari, הודעות, WhatsApp, דוא\"ל…) כדי לבדוק אותו תחילה.",
        "activate_step_qr": "או סרוק קוד QR, או הדבק קישור במסך הבית.",
        "activate_step_safe": "קישורים בטוחים — ואלה שתבחר להמשיך אליהם — ייפתחו בדפדפן ברירת המחדל שלך.",
        "activate_note": "טיפ: בחר באיזה דפדפן ייפתחו קישורים בטוחים. iOS מתיר רק לאפליקציות דפדפן מלאות להיות ברירת המחדל, ולכן AntiPhishing בודקת קישורים דרך שיתוף במקום להחליף את הדפדפן.",
        "open_settings": "פתח הגדרות דפדפן ברירת מחדל",
        "activate_done": "הפעל הגנה",
        "verifying_protection": "בודק שההגנה פועלת…",
        "protection_active_banner": "✅ ההגנה פעילה — בדיקת הקישורים עובדת",
        "protection_active_offline": "⚠️ ההגנה פעילה, אך שירות הבדיקה אינו זמין",
        "protection_off_banner": "ההגנה כובתה",
        // Safari Web Extension protection
        "safari_protection_title": "הגנת Safari",
        "sp_status_storage_error": "האחסון המשותף אינו זמין",
        "sp_status_storage_error_detail": "האפליקציה לא מצליחה לגשת לאחסון המשותף ולכן לא ניתן לשמור את נתוני ההגנה. נסה להתקין מחדש.",
        "sp_status_updating": "מעדכן את מסד ההגנה…",
        "sp_status_updating_detail": "מוריד את נתוני האיומים העדכניים.",
        "sp_status_no_db": "ההגנה עדיין לא מוכנה",
        "sp_status_no_db_detail": "מסד נתוני ההגנה טרם הורד. הורד אותו כדי להגן על Safari.",
        "sp_status_no_db_offline": "אין חיבור — ההגנה לא מוכנה",
        "sp_status_no_db_offline_detail": "אין חיבור לאינטרנט ואין מסד נתונים מקומי. התחבר לאינטרנט ונסה שוב.",
        "sp_status_active": "ההגנה פעילה",
        "sp_status_active_detail": "Safari מוגן עם נתוני איומים עדכניים.",
        "sp_status_update_available": "ההגנה פעילה — קיים עדכון",
        "sp_status_update_available_detail": "לשרת יש נתוני איומים חדשים מהעותק המקומי שלך. עדכן כדי להישאר מוגן במלואך.",
        "sp_status_active_stale": "ההגנה פעילה — המסד ישן",
        "sp_status_active_stale_detail": "מסד הנתונים המקומי לא עודכן לאחרונה. עדכן כשמתאפשר.",
        "sp_status_offline": "ההגנה פעילה — לא מקוון",
        "sp_status_offline_detail": "שירות העדכון אינו זמין. Safari מוגן באמצעות המסד האחרון שהורד.",
        "sp_status_update_failed": "העדכון האחרון נכשל",
        "sp_status_update_failed_detail": "המסד הקודם עדיין פעיל ומגן על Safari. נסה לעדכן שוב.",
        "sp_master_off_detail": "ההגנה הפעילה כבויה, ולכן דפי Safari אינם נבדקים. הפעל אותה ממסך הבית.",
        "sp_ext_enabled": "תוסף Safari פעיל",
        "sp_ext_not_detected": "תוסף Safari לא זוהה",
        "sp_ext_last_seen": "פעילות אחרונה:",
        "sp_ext_not_detected_detail": "iOS מחייב אותך להפעיל את התוסף באופן ידני בהגדרות ולאשר גישה לאתרים.",
        "sp_ext_guide_button": "איך מפעילים את תוסף Safari",
        "sp_toast_toggle": "הצג אישור בדיקה ב-Safari",
        "sp_toast_toggle_detail": "כשהמתג דולק, כל דף שנפתח ב-Safari מציג חיווי סטטוס קצר — נבדק ובטוח, חסר מסד נתונים, או שההגנה כבויה. בדיקה קלה מקצה לקצה; כבה לגלישה שקטה.",
        "sp_db_section": "מסד נתוני ההגנה",
        "sp_db_version": "גרסה",
        "sp_db_updated": "עודכן לאחרונה",
        "sp_db_domains": "דומיינים מוגנים (במכשיר)",
        "sp_db_server_domains": "דומיינים בשרת",
        "sp_db_checked": "נבדק לאחרונה",
        "sp_db_none": "מסד הנתונים טרם הורד. לא ניתן להגן על Safari עד להורדתו.",
        "sp_download_button": "הורד את מסד ההגנה",
        "sp_update_button": "עדכן את מסד ההגנה",
        "sp_note_safari_only": "תוסף AntiPhishing מגן על Safari בלבד. אם דפדפן אחר (כמו Chrome) מוגדר כברירת מחדל, קישורים ייפתחו בו ללא הגנה — שקול להגדיר את Safari כדפדפן ברירת המחדל.",
        "sp_progress_left": "נותרו",
        "sp_checking_freshness": "בודק עדכונים…",
        "sp_db_duration": "משך העדכון האחרון",
        "sp_feed_issues": "חלק מהמקורות נתקלו בבעיה בעדכון האחרון:",
        "sp_recent_visits_title": "נבדקו לאחרונה ב-Safari",
        "sp_recent_visits_empty": "עדיין לא נבדקו דפים. גלוש ב-Safari כשהתוסף מופעל, והם יופיעו כאן.",
        "sp_visit_verdict_safe": "בטוח",
        "sp_visit_verdict_malicious": "נחסם",
        "sp_visit_verdict_allowlisted": "אושר",
        "sp_visit_verdict_off": "ההגנה כבויה",
        "sp_visit_verdict_unprotected": "לא מוגן",
        "sp_phase_contacting": "יוצר קשר עם השרת…",
        "sp_phase_downloading": "מוריד רשימות איומים…",
        "sp_phase_building": "בונה מסד נתונים…",
        "sp_phase_validating": "מאמת את הנתונים שהורדו…",
        "sp_phase_activating": "מפעיל את המסד החדש…",
        "sp_update_success": "✅ מסד הנתונים עודכן בהצלחה",
        "sp_update_already_current": "✅ מסד הנתונים כבר עדכני",
        "err_update_storage": "האחסון המשותף אינו זמין — לא ניתן לשמור את מסד הנתונים.",
        "err_update_offline_db": "לא ניתן להגיע למקורות העדכון. Safari נשאר מוגן עם המסד האחרון שהורד.",
        "err_update_offline_nodb": "לא ניתן להוריד את מסד הנתונים. בדוק את חיבור האינטרנט ונסה שוב.",
        "err_update_invalid_data": "הנתונים שהורדו אינם תקינים ולא הופעלו. המסד הקודם נשאר בשימוש.",
        "err_update_generic": "העדכון נכשל. המסד הקודם נשאר בשימוש.",
        // Enable-extension guide
        "ext_guide_title": "הפעלת תוסף Safari",
        "ext_guide_intro": "Apple מחייבת להפעיל תוספי Safari באופן ידני. זה לוקח כדקה:",
        "ext_guide_step1": "פתח הגדרות ▸ אפליקציות ▸ Safari ▸ תוספים (בגרסאות ישנות: הגדרות ▸ Safari ▸ תוספים).",
        "ext_guide_step2": "הקש על AntiPhishing והפעל את \"אפשר תוסף\".",
        "ext_guide_step3": "תחת הרשאות, אשר גישה ל\"כל אתרי האינטרנט\" כדי שניתן יהיה לבדוק דפים.",
        "ext_guide_step4": "חזור לכאן — הסטטוס יתעדכן אחרי שהתוסף יבדוק את הדף הראשון ב-Safari.",
        "ext_guide_note": "התוסף בודק כתובות דפים קודם כל מול מסד הנתונים שבמכשיר, לגמרי במצב לא מקוון. רק כשאתר אינו ידוע כבטוח או כזדוני, הכתובת שלו נשלחת לשרת של AntiPhishing לבדיקת סיכון מעמיקה יותר.",
        "ext_guide_open_settings": "פתח הגדרות",
        // Allowlist management
        "allowlist_title": "דומיינים מאושרים",
        "allowlist_empty": "אין דומיינים מאושרים. כשתלחץ על \"המשך בכל זאת\" בדף אזהרה ב-Safari, הדומיין יופיע כאן.",
        "allowlist_footer": "אישורים פגים אוטומטית אחרי 24 שעות. הסרת אישור מחזירה את החסימה לאותו דומיין.",
        "allowlist_clear_expired": "הסר שפג תוקפם",
        "allowlist_clear_all": "הסר הכול",
        "allowlist_clear_all_confirm": "להסיר את כל הדומיינים המאושרים? החסימה תחודש לכולם.",
        "allowlist_approved": "אושר:",
        "allowlist_expires": "פג תוקף",
        "allowlist_expired_at": "פג תוקף",
        "allowlist_expired": "פג תוקף"
    ]

    static func string(_ key: String, _ lang: AppLanguage) -> String {
        let table = (lang == .hebrew) ? he : en
        return table[key] ?? en[key] ?? key
    }
}
